"""Save frank's QR code from Mastodon app to frequently used directory for easy access."""

from typing import Any

from loguru import logger

from mobile_world.runtime.app_helpers import mastodon
from mobile_world.runtime.controller import AndroidController
from mobile_world.runtime.utils.helpers import execute_adb
from mobile_world.tasks.base import BaseTask

# Task constants
SOURCE_USERNAME = "frank"
TARGET_PATH = "/sdcard/mastodon_save"


def _check_qr_code_saved(target_path: str, username: str) -> tuple[bool, str]:
    """Check if QR code was saved to the frequently used directory with correct filename."""
    try:
        # Check if target directory exists
        result = execute_adb(f"shell ls -l {target_path}")
        if not result.success:
            return False, f"Frequently used directory does not exist: {target_path}"

        lines = result.output.strip().split("\n")

        # Parse saved files and check for QR code with correct username
        matching_files = []
        all_files = []

        for line in lines:
            if not line.strip() or line.startswith("total") or line.startswith("d"):
                continue

            parts = line.split()
            if len(parts) >= 8:
                filename = " ".join(parts[7:])
                all_files.append(filename)

                # Check if filename matches pattern: {username}_{ip}.png
                # e.g., frank_10.0.2.2.png
                if filename.startswith(f"{username}_") and filename.endswith(".png"):
                    matching_files.append(filename)

        logger.info(f"All files found in {target_path}: {all_files}")
        logger.info(f"QR code files matching '{username}_*.png' pattern: {matching_files}")

        # Check if QR code with correct username was found
        if len(matching_files) == 0:
            return (
                False,
                f"No QR code found with username '{username}' (expected format: {username}_*.png)",
            )

        # Verify the matching files are valid images by checking their size
        for saved_file in matching_files:
            remote_path = f"{target_path}/{saved_file}"
            size_result = execute_adb(f"shell stat -c %s {remote_path}")
            if size_result.success:
                try:
                    file_size = int(size_result.output.strip())
                    if file_size > 0:
                        return True, f"QR code saved successfully: {saved_file}"
                except ValueError:
                    logger.warning(f"Failed to get file size for {saved_file}")
                    continue

        return False, f"Found QR code files but they appear to be invalid: {matching_files}"

    except Exception as e:
        logger.error(f"Error checking saved QR code: {e}")
        return False, f"Error during validation: {str(e)}"


class MastodonDumpQcodeAskUserTask(BaseTask):
    """
    Save frank's QR code from Mastodon app to frequently used directory for easy access.

    The QR code is generated by the Mastodon app (not from posts) and should be saved
    with filename format: {username}_{ip}.png (e.g., frank_10.0.2.2.png)
    """

    task_tags = {"agent-user-interaction", "lang-en"}

    goal = "Save the frank's QR code on Mastodon to my frequently used directory for easy access."

    # Use constants defined at module level
    source_username = SOURCE_USERNAME
    target_path = TARGET_PATH

    def __init__(self, params: dict[str, Any] = None):
        super().__init__(params)

    app_names = {
        "Mastodon",
    }

    def initialize_task_hook(self, controller: AndroidController) -> bool:
        # Set relevant_information to provide context about the frequently used directory
        self.relevant_information = f"The frequently used directory is {self.target_path}"

        try:
            mastodon.start_mastodon_backend()
        except Exception as e:
            logger.error(f"Failed to start Mastodon backend: {e}")
            return False

        logger.info(
            f"Task: Save {self.source_username}'s QR code from Mastodon app to frequently used directory: {self.target_path}"
        )

        # Clean up target directory if it exists from previous runs
        result = execute_adb(f"shell ls {self.target_path}")
        if result.success:
            logger.info(f"Cleaning up existing target directory: {self.target_path}")
            execute_adb(f"shell rm -rf {self.target_path}")

        return True

    def is_successful(self, controller: AndroidController) -> tuple[float, str]:
        """
        Check if frank's QR code was saved to the frequently used directory successfully.

        Checks:
        - Frequently used directory exists on device
        - QR code image was saved with correct filename format: {username}_{ip}.png
        - Saved file is a valid image

        Example expected filename: frank_10.0.2.2.png
        """
        self._check_is_initialized()

        assert mastodon.is_mastodon_healthy()

        success, message = _check_qr_code_saved(
            target_path=self.target_path, username=self.source_username
        )

        if success:
            return 1.0, message
        else:
            return 0.0, message

    def tear_down(self, controller: AndroidController) -> bool:
        """Clean up task - remove downloaded QR code images and stop Mastodon backend."""
        super().tear_down(controller)

        try:
            # Remove frequently used directory with QR code images
            result = execute_adb(f"shell ls {self.target_path}")
            if result.success:
                logger.info(f"Cleaning up frequently used directory: {self.target_path}")
                execute_adb(f"shell rm -rf {self.target_path}")
        except Exception as e:
            logger.error(f"Error cleaning up target directory: {e}")

        # Stop Mastodon backend
        try:
            mastodon.stop_mastodon_backend()
        except Exception as e:
            logger.error(f"Failed to stop Mastodon backend: {e}")
            return False

        return True
